#!/bin/bash
# obj2gltf AppImage build script — reproducible from a clean checkout.
# Tested on the campaign build VM (x86-64), node v24.20.0, npm 10.9.4.
set -e
WORK="${WORK:-$HOME/workspace/build/appimage-campaign}"
T="$WORK/obj2gltf"

# 1. Clone and fetch dependencies from source
mkdir -p "$T" && cd "$T"
[ -d repo ] || git clone https://github.com/CesiumGS/obj2gltf repo
cd repo && git checkout 979a24a770154e8e9b964a554f86436dc4cafafa && cd ..
cd repo
npm install --no-audit --no-fund
npm prune --omit=dev
cd ..

# 2. Stage the AppDir (node runtime + package; AppRun passes args through)
APPDIR="$T/Obj2gltf.AppDir"
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin" "$APPDIR/usr/lib/obj2gltf"
cp -L /usr/bin/node "$APPDIR/usr/bin/node"
cp repo/package.json "$APPDIR/usr/lib/obj2gltf/"
cp -r repo/bin repo/lib repo/node_modules "$APPDIR/usr/lib/obj2gltf/"
# (icon + Obj2gltf.desktop generated by the packaging step)

cat > "$APPDIR/AppRun" <<'EOF'
#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"
exec "$HERE/usr/bin/node" "$HERE/usr/lib/obj2gltf/bin/obj2gltf.js" "$@"
EOF
chmod +x "$APPDIR/AppRun"

# 3. Package (appimagetool extracted root expected at $WORK/appimagetool-root)
cd "$WORK"
ARCH=x86_64 "$WORK/appimagetool-root/AppRun" "$APPDIR" "Obj2gltf-x86_64.AppImage"
# -> $WORK/Obj2gltf-x86_64.AppImage
